### ISSUE TITLE
Verify user testing before release

### ISSUE THREAD

**Issue by ashcrow** [ashcrow/flask-track-usage#27]
Ask @gouthambs to help test before releasing 1.1.0.

**Comment by gouthambs** [comment]
I modified the test cases and the API's are functional. What more would you like to be added here?

**Comment by ashcrow** [comment]
@gouthambs Sometime after all the issues are closed I'd just like someone else other than myself to install and verify things are working. Really I just want myself and someone (you're a good candidate :-D) to give it a go and make sure there isn't any glaring bugs. Nothing crazy.

**Comment by ashcrow** [comment]
Released 1.1.0

- PyPi: https://pypi.python.org/pypi/Flask-Track-Usage/1.1.0
- Docs: https://pythonhosted.org/Flask-Track-Usage/
