### ISSUE TITLE
Incompatible with Redis 3

### ISSUE THREAD

**Issue by M0r13n** [ashcrow/flask-track-usage#54]
RedisStorage is not compatible with newer versions of Redis. When trying to store the data in Redis an redis.exceptions.DataError is thrown (see [this line](https://github.com/ashcrow/flask-track-usage/blob/f98c3bbeec79c3fad0e5da3c2553ed1fc825a7e4/src/flask_track_usage/storage/redis_db.py#L79). This is because Redis 3.0 only accepts keys and values as bytes, strings or numbers as stated [here](https://github.com/andymccurdy/redis-py/issues/1071).

Also it would be nice, if it would be possible to set up Redis with a connection url instead of using host and port. Many apps store their Redis connection like that and platforms like Scalingo also provide only the url as an env var.

**Comment by ashcrow** [comment]
Fixed with #55
