### ISSUE TITLE
SQL table 'flask_usage.path' length (32) is too short

### ISSUE THREAD

**Issue by olliebreeden** [ashcrow/flask-track-usage#56]
My website path is usually longer than 32 characters as I use uuid4 to encode an object id. Would you be able to increase this to 128 or even 256?

**Comment by ashcrow** [comment]
https://github.com/ashcrow/flask-track-usage/pull/57

**Comment by ashcrow** [comment]
The PR you provided should do most of the trick. There are two other things that are needed (which I'm happy to handle):

1. Travis CI configuration looks like it needs updating for MySQL
2. alembic migration is needed for those who are updating from an instance that is already installed

**Comment by ashcrow** [comment]
This is now fixed and "migratable" in `master`.
